app/models.py
# app/models.py

# from flask_login import UserMixin
# from werkzeug.security import generate_password_hash, check_password_hash

from app import db

class Job(db.Model):
    """
    Create an Job table
    """

    # Ensures the table will be named in plural
    __tablename__ = 'jobs'

    jobID = db.Column(db.Integer, primary_key=True)
    recordType = db.Column(db.Integer)
    jobTitle = db.Column(db.String(60))
    employerName = db.Column(db.String(60))
    jobDescription = db.Column(db.String(256))
    locations = ""
    url = db.Column(db.String(256))
    postedDate = db.Column(db.String(60))
    expiryDate = db.Column(db.String(60))
    salaryType = db.Column(db.String(60))
    salaryMultiplier = db.Column(db.Integer)
    salaryMin = db.Column(db.Integer)
    salaryMax = db.Column(db.Integer)
    jobType = ""
    majorProject = ""

class Location(db.Model):
    """
    Create an Location table
    """

    # Name the for locations
    __tablename__ = 'locations'

    city = db.Column(db.String(60), primary_key=True)
    region = ""
    regionName = db.Column(db.String(60))
    province = db.Column(db.String(60))

class Job_Location(db.Model):
    """
    Create an Job Location table that represents the many to many
    """

    # Name the table for jobs_locations
    __tablename__ = 'jobs_locations'

    jlid = db.Column(db.String(60), primary_key=True)
    jobID = db.Column(db.Integer, db.ForeignKey('jobs.jobID'))
    city = db.Column(db.String(60), db.ForeignKey('locations.city'))

class JobType(db.Model):
    """
    Create an Job Type table
    """

    # Name the for jobtypes
    __tablename__ = 'jobtypes'

    jtid = db.Column(db.String(60), primary_key=True)
    id = db.Column(db.Integer)
    jobID = db.Column(db.Integer, db.ForeignKey('jobs.jobID'))
    caption = db.Column(db.String(60))

class Region(db.Model):
    """
    Create an Region table
    """

    __tablename__ = 'regions'

    rid = db.Column(db.String(60), primary_key=True)
    id = db.Column(db.Integer)
    city = db.Column(db.String(60), db.ForeignKey('locations.city'))
    caption = db.Column(db.String(60))

class MajorProject(db.Model):
    """
    Create an Major Projects table
    """

    __tablename__ = 'majorprojects'

    mpid = db.Column(db.String(60), primary_key=True)
    id = db.Column(db.Integer)
    jobID = db.Column(db.Integer, db.ForeignKey('jobs.jobID'))
    caption = db.Column(db.String(60))

app/__init__.py
# app/__init__.py

# third-party imports
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate

# local imports
from config import app_config

# db variable initialization
db = SQLAlchemy()

def create_app(config_name):
    # flask config
    app = Flask(__name__, instance_relative_config=True)
    app.config.from_object(app_config[config_name])
    app.config.from_pyfile('config.py')

    # database init
    db.init_app(app)

    migrate = Migrate(app, db)

    # load the db models
    from app import models

    # create the blueprints
    from .home import home as home_blueprint
    app.register_blueprint(home_blueprint)

    return app

app/home/__init__.py
from flask import Blueprint

home = Blueprint('home', __name__)

from . import views

app/home/views.py
# app/home/views.py

from flask import render_template

from . import home

@home.route('/')
def homepage():
    """
    Render the homepage template on the / route
    """
    return render_template('home/index.html', title='Welcome')

app/templates/base.html
<!-- app/templates/base.html -->

<html lang="en">
<head>
    <title>{{ title }} | Project MASH</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/style.css') }}" rel="stylesheet">
    <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon.ico') }}">
</head>
<body>
    <nav class="navbar navbar-default navbar-fixed-top topnav" role="navigation">
        <div class="container topnav">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand topnav" href="{{ url_for('home.homepage') }}">Project Mash</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-right">
                  <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
              </ul>
          </div>
        </div>
    </nav>
    <div class="wrapper">
      {% block body %}
      {% endblock %}
      <div class="push"></div>
    </div>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <ul class="list-inline">
                        <li><a href="{{ url_for('home.homepage') }}">Home</a></li>
                    </ul>
                    <p class="copyright text-muted small">Copyright © 2016. All Rights Reserved</p>
                </div>
            </div>
        </div>
    </footer>
</body>
</html>

app/templates/home/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="intro-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="intro-message">
                    <h1>Project Mash</h1>
                    <h3>Lets find us some potatos!</h3>
                    <hr class="intro-divider">
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}